### ISSUE TITLE
Xcode 6.3/Swift 1.2 compatibility issues

### ISSUE THREAD

**Issue by colddiver** [ndavon/NDHpple#10]
Getting a "Module file was created by an older version of the compiler" in a project that uses NDHpple. Haven't yet had a chance to track the issue but will report back here when I find something.

**Comment by colddiver** [comment]
Ok - I fixed that one by cleaning ~/Library/Developer/Xcode/DerivedData. I had to tweak the code a bit to remove some errors (minor stuff)...

**Comment by vittoriom** [comment]
Does that mean that the module can be compiled with Swift 1.2 without any modification to the source code?

**Comment by vittoriom** [comment]
Do you have a fork I can clone to make the module work with Swift 1.2?

**Comment by vittoriom** [comment]
nevermind, it looks like it's just a few minor changes :+1:
