### ISSUE TITLE
Problem after adding the files to my project

### ISSUE THREAD

**Issue by fboulegue** [ndavon/NDHpple#7]
![test](https://cloud.githubusercontent.com/assets/2719590/4973976/4d5c61c0-68c7-11e4-9357-05c944cecb0c.png)

**Comment by vittoriom** [comment]
I also had the same issue, then I had a look at the original project and I found in the build settings these 2 flags:

Other linker flags: -lxml2
Header search paths: $(SDKROOT)/usr/include/libxml2

After I added these two settings, the build succeeded for me

**Comment by Huato115** [comment]
i still had same problem therefore i added header search path andlinker flag . i stucked on this for 1 week . Please help.

**Comment by escully27** [comment]
@vittoriom wanted to say thanks for your observation. I was frustrated with the same issue but you saved me!

**Comment by vittoriom** [comment]
@escully27 glad it helped! :)

**Comment by ndavon** [comment]
The project has been updated to use the Swift Package Manager which will hopefully prevent such problems.
